berkeleydb/db-5.3.28.tar.gz:
  size: 35090431
  sha: fa3f8a41ad5101f43d08bc0efb6241c9b6fc1ae9
golang/go-linux-amd64.tar.gz:
  size: 84021919
  sha: 2e5baf03d1590e048c84d1d5b4b6f2540efaaea1
golang/go-version.txt:
  size: 65
  sha: f369bdd973099d4b9e212384bbecb880ad7ba5e1
openldap/openldap-2.4.44.tgz:
  size: 5658830
  sha: 016a738d050a68d388602a74b5e991035cdba149
python/Python-2.7.13.tar.xz:
  size: 12495628
  sha: 18a8f30a0356c751b8d0ea6f76e764cab13ee046
python/pip-9.0.1-py2.py3-none-any.whl:
  size: 1254803
  sha: c70393185d27ae8b49a117e6dcc18bc5f8f3a1c3
python/pyldap-2.4.37.tar.gz:
  size: 328629
  sha: 913a0771e91dcfa35ef9e19ff2fadb8418ee0438
python/requests-v2.18.4.tar.gz:
  size: 3040025
  sha: c503cf6df6d98f975ca71dbb4f7c635a6d8c9ab6
python/setuptools-36.5.0-py2.py3-none-any.whl:
  size: 478810
  sha: 0cfffdb11d439fe3b7887741faa87d5ff67f6ee0
python/virtualenv-15.1.0-py2.py3-none-any.whl:
  size: 1820727
  sha: 0def1fa94de51aa56e24eaefe2173df7249e6ded
python/wheel-0.30.0-py2.py3-none-any.whl:
  size: 49751
  sha: 11694b2cfb611fd4accb1135c7d0fef9db4cd926
sasl/cyrus-sasl-2.1.26.tar.gz:
  size: 5220231
  sha: d6669fb91434192529bd13ee95737a8a5040241c
splunk/rfc5424-syslog_11.tgz:
  size: 2321
  sha: 7ff46da6351183dfd8eefe92140c99307abce76b
splunk/splunk-add-on-for-cloud-foundry_020.tgz:
  size: 24761
  sha: 352cbbd6d0e04e9b89c1d903d83156c4abce1a84
splunk/splunk-linux-x86_64.tgz:
  size: 227135261
  sha: 637043d9a5f4a3a093e8b01586357647e179f78c
splunk/splunk-version.txt:
  size: 108
  sha: 79483b733d45199615f006a36cb11897db49637c
splunk/website-monitoring_26.tgz:
  size: 1360994
  sha: 433ba138a363917ba307260bc773611a4f8e9c50
